### ISSUE TITLE
Token visible

### ISSUE THREAD

**Issue by DevNullGamer** [Spajciuch/Mieciu#1]
Hi.

I just wanted to let you know that your bot token is visible in your latest commit. 
You might want to look into gitignore: https://help.github.com/articles/ignoring-files/

Best regards.

**Comment by Spajciuch** [comment]
It's old token

**Comment by Spajciuch** [comment]
In `config.json?` @ziclow

**Comment by DevNullGamer** [comment]
Yes, then one i config.json.
I didnt test if the token was active or not.

**Comment by Spajciuch** [comment]
Ok, I will remove old token from config
